### PR TITLE
Add budget functionality

### LINKED ISSUE #15: Set budget
As a user, I can set budgets so that I can manage my expenses better

### LINKED ISSUE #56: Exceptions for budget
empty desc
wrong input

### PR DESCRIPTION
**Pull request by ryan1604**
Fixes #15
Fixes #56

### CODE REVIEW

**Comment by ryan1604** [comment]
dont merge yet

**Comment by ryan1604** [comment]
Some changes made:

- Add budget function
- Update budget function
- Automatically update current budget(if there is one) when new expense is added
- Remove redundant get() and size() in cashFlowList
- Remove redundant "NAME" from command prefix

**Review by NeoMinWei — APPROVED** [review]
LGTM

**Review by wwweert123 — APPROVED** [review]
LGTM

**Review by hshiah — APPROVED** [review]
LGTM

**Pull request merged**
